name: jamesa
favicon: null
layout_spectrum: 0.15124978334642947
typography_spectrum: 0.8666787433903664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6793436175212264
  lightness: 0.7583888187073171
  saturation: 0.013709209393709898
  rhythmicContrast: 0.5952791986055672
purpose: []
